SELECT
    e.global_event_id,
    e.event_date,
    e.event_month_year,
    e.event_year,
    e.fraction_date,
    e.actor1_code,
    e.actor1_name,
    e.actor1_cpuntry_code,
    e.actor1_known_group_code,
    e.actor1_ethnic_code,
    e.actor1_religion1_code,
    e.actor1_religion2_code,
    e.actor1_type1_code,
    e.actor1_type2_code,
    e.actor1_type3_code,
    e.actor2_code,
    e.actor2_name,
    e.actor2_country_code,
    e.actor2_known_group_code,
    e.actor2_ethnic_code,
    e.actor2_religion1_code,
    e.actor2_religion2_code,
    e.actor2_type1_code,
    e.actor2_type2_code,
    e.actor2_type3_code,
    e.is_root_event,
    e.event_code,
    e.event_base_code,
    e.event_root_code,
    e.quad_class,
    e.goldstein_scale,
    e.num_mentions,
    e.num_sources,
    e.num_articles,
    e.avg_tone,
    e.actor1_geo_type,
    e.actor1_geo_full_name,
    e.actor1_geo_country_code,
    e.actor1_geo_adm1_code,
    e.actor1_geo_adm2_code,
    e.actor1_geo_lat,
    e.actor1_geo_long,
    e.actor1_geo_feature_id,
    e.actor2_geo_type,
    e.actor2_geo_full_name,
    e.actor2_geo_country_code,
    e.actor2_geo_adm1_code,
    e.actor2_geo_adm2_code,
    e.actor2_geo_lat,
    e.actor2_geo_long,
    e.actor2_geo_feature_id,
    e.action_geo_type,
    e.action_geo_full_name,
    e.action_geo_country_code,
    e.action_geo_adm1_code,
    e.action_geo_adm2_code,
    e.action_geo_lat,
    e.action_geo_long,
    e.action_geo_feature_id,
    e.date_added,
    e.source_url,
    f.short_form_name,
    gt.geo_type_name AS action_geo_type_name

FROM {{ ref('stg_external_gdelt_events_csv') }} AS e
    LEFT JOIN {{ ref('dim_fips') }} AS f
        ON e.action_geo_country_code = f.code
    LEFT JOIN {{ ref('dim_geo_types') }} AS gt
        ON e.action_geo_type = gt.geo_type_id
