id: ge_gcp_copy_data
namespace: gdelt_events
description: |
  Flow for processing data from external table to partitioned table in BigQuery.

variables:
  source_table: "{{ kv('GCP_DATASET') }}.{{ kv('GCP_TABLE_EXTERNAL') }}"
  destination_table: "{{ kv('GCP_DATASET') }}.{{kv('GCP_TABLE_PARTITIONED') }}"

tasks:
  - id: copy_data
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      MERGE `{{ kv('GCP_PROJECT_ID') }}.{{ render(vars.destination_table) }}` T
      USING `{{ kv('GCP_PROJECT_ID') }}.{{ render(vars.source_table) }}` S
      ON T.globaleventid = S.globaleventid

      WHEN NOT MATCHED THEN
        INSERT (
          GLOBALEVENTID,
          SQLDATE,
          MonthYear,
          Year,
          FractionDate,
          Actor1Code,
          Actor1Name,
          Actor1CountryCode,
          Actor1KnownGroupCode,
          Actor1EthnicCode,
          Actor1Religion1Code,
          Actor1Religion2Code,
          Actor1Type1Code,
          Actor1Type2Code,
          Actor1Type3Code,
          Actor2Code,
          Actor2Name,
          Actor2CountryCode,
          Actor2KnownGroupCode,
          Actor2EthnicCode,
          Actor2Religion1Code,
          Actor2Religion2Code,
          Actor2Type1Code,
          Actor2Type2Code,
          Actor2Type3Code,
          IsRootEvent,
          EventCode,
          EventBaseCode,
          EventRootCode,
          QuadClass,
          GoldsteinScale,
          NumMentions,
          NumSources,
          NumArticles,
          AvgTone,
          Actor1Geo_Type,
          Actor1Geo_FullName,
          Actor1Geo_CountryCode,
          Actor1Geo_ADM1Code,
          Actor1Geo_ADM2Code,
          Actor1Geo_Lat,
          Actor1Geo_Long,
          Actor1Geo_FeatureID,
          Actor2Geo_Type,
          Actor2Geo_FullName,
          Actor2Geo_CountryCode,
          Actor2Geo_ADM1Code,
          Actor2Geo_ADM2Code,
          Actor2Geo_Lat,
          Actor2Geo_Long,
          Actor2Geo_FeatureID,
          ActionGeo_Type,
          ActionGeo_FullName,
          ActionGeo_CountryCode,
          ActionGeo_ADM1Code,
          ActionGeo_ADM2Code,
          ActionGeo_Lat,
          ActionGeo_Long,
          ActionGeo_FeatureID,
          DATEADDED,
          SOURCEURL
        )
        VALUES (
          S.GLOBALEVENTID,
          PARSE_DATE('%Y%m%d', CAST(S.SQLDATE AS STRING)),
          S.MonthYear,
          S.Year,
          S.FractionDate,
          S.Actor1Code,
          S.Actor1Name,
          S.Actor1CountryCode,
          S.Actor1KnownGroupCode,
          S.Actor1EthnicCode,
          S.Actor1Religion1Code,
          S.Actor1Religion2Code,
          S.Actor1Type1Code,
          S.Actor1Type2Code,
          S.Actor1Type3Code,
          S.Actor2Code,
          S.Actor2Name,
          S.Actor2CountryCode,
          S.Actor2KnownGroupCode,
          S.Actor2EthnicCode,
          S.Actor2Religion1Code,
          S.Actor2Religion2Code,
          S.Actor2Type1Code,
          S.Actor2Type2Code,
          S.Actor2Type3Code,
          S.IsRootEvent,
          S.EventCode,
          S.EventBaseCode,
          S.EventRootCode,
          S.QuadClass,
          S.GoldsteinScale,
          S.NumMentions,
          S.NumSources,
          S.NumArticles,
          S.AvgTone,
          S.Actor1Geo_Type,
          S.Actor1Geo_FullName,
          S.Actor1Geo_CountryCode,
          S.Actor1Geo_ADM1Code,
          S.Actor1Geo_ADM2Code,
          S.Actor1Geo_Lat,
          S.Actor1Geo_Long,
          S.Actor1Geo_FeatureID,
          S.Actor2Geo_Type,
          S.Actor2Geo_FullName,
          S.Actor2Geo_CountryCode,
          S.Actor2Geo_ADM1Code,
          S.Actor2Geo_ADM2Code,
          S.Actor2Geo_Lat,
          S.Actor2Geo_Long,
          S.Actor2Geo_FeatureID,
          S.ActionGeo_Type,
          S.ActionGeo_FullName,
          S.ActionGeo_CountryCode,
          S.ActionGeo_ADM1Code,
          S.ActionGeo_ADM2Code,
          S.ActionGeo_Lat,
          S.ActionGeo_Long,
          S.ActionGeo_FeatureID,
          S.DATEADDED,
          S.SOURCEURL
        );

  - id: purge_files
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
    description: If you'd like to explore Kestra outputs, disable it.
    disabled: false

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

triggers:
  - id: hourly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 * * * *"   # Upload every hour
