version: 2

sources:
  - name: raw_data
    description: "Raw data sources for the project"
    database: "{{ target.project }}" # BigQuery Project ID
    schema: "{{ target.dataset }}" # BigQuery Dataset Name
    tables:
      - name: external_gdelt_events_csv
        description: "Accumulated raw data of events"